#!/bin/bash

clear
failed=0

while true; do
  date
  ./build/etracker -p $1 -i 300 --min-interval 300 -e 300 -k --nofile 64000 --core -1 -f $failed -a 0.5
  echo Exit code: $?
  ((failed=failed+1))
  sleep 1
done
